package com.example.focusito03.navegacion

import com.example.focusito03.interfaces.estu


sealed class Screen(val route: String
){
    object inicio: Screen("pantallaprincipal")
    object login: Screen("login")
    object registrate: Screen("registrate")
    object roles: Screen("roles")
    object profesor: Screen("profesor")
    object estudiante: Screen("estudiante")
    object puntos: Screen("puntos")
    object actividades: Screen("actividades")
    //actividades: cuentos
    object fabulasypoemas: Screen("cuentos")
    object fabulas: Screen("fabulas")
    object fabula1: Screen("fabula1")
    object contifabula1: Screen("contifabula1")
    object fabula2: Screen("fabula2")
    object contifabula2: Screen("contiz3")
    object contifabula: Screen("contifabula2")
    object fabula3: Screen("fabula3")
    object contil: Screen("contil")
    object contil2: Screen("contil2")
    object poemas: Screen("poemas")
    object poema1: Screen("poema1")
    object poema2: Screen("poema2")
    object actividadnoregistrada: Screen("actividadnoregistrada")
    // Actividades: preguntas y completar fraces
    object quiz: Screen("quiz")
    object quiz1: Screen("quiz1")
    object quiz1pregunta1: Screen("quiz1pregunta1")
    object quiz1pregunta2: Screen("quiz1pregunta2")
    object quiz1pregunta3: Screen("quiz1pregunta3")
    object quiz1pregunta4: Screen("quiz1pregunta4")
    object quiz1pregunta5: Screen("quiz1pregunta5")
    object terminastequiz1: Screen("terminastequiz1")
    object comensemosquiz2: Screen("comencemosquiz2")
    object quiz2: Screen("quiz2")
    object quiz2pregunta1: Screen("quiz2pregunta1")
    object quiz2pregunta2: Screen("quiz2pregunta2")
    object quiz2pregunta3: Screen("quiz2pregunta3")
    object quiz3: Screen("quiz3")
    object quiz3pregunta1: Screen("quiz3pregunta1")
    object quiz3pregunta2 : Screen("quiz3pregunta2")
    object quiz3pregunta3: Screen("quiz3pregunta3")
    object quiz3pregunta4: Screen("quiz3pregunta4")
    object quiz3pregunta5: Screen("quiz3pregunta5")
    object terminastequiz3: Screen("terminastequiz3")
    object comencemosquiz4: Screen("comencemosquiz4")
    object quiz4pregunta1: Screen("quiz4pregunta1")
    object quiz4pregunta2: Screen("quiz4pregunta2")
    object quiz4pregunta3: Screen("quiz4pregunta3")
    object quiz4pregunta4: Screen("quiz4pregunta4")
    object quiz4pregunta5: Screen("quiz4pregunta5")
    object quiz4pregunta6: Screen("quiz4pregunta6")
    object quiz4pregunta7: Screen("quiz4pregunta7")
    object quiz4pregunta8: Screen("quiz4pregunta8")
}